# See https://docs.docker.com/compose/compose-file/ for information about what
# commands you can use in this file.
#
# Note that you must use the `docker stack deploy` command, with any required
# command line flags, in order to actually get any replicas started. That
# command requires that a docker swarm is already running in order to function.

version: "3"
services:
  bootstrap:
    image: kadlab:latest
    stdin_open: true
    tty: true
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - ../:/code
      - ./init/bootstrap/:/init
    networks:
      kademlia_network:
        ipv4_address: 10.0.0.2
  kademliaNodes:
    image: kadlab:latest
    stdin_open: true
    tty: true
    deploy:
      replicas: 50  
#        resources:
#           limits:
#              cpus: "0.1"
#              memory: 50M
      restart_policy:
        condition: on-failure
#    ports:
#      - "4000:80"
    networks:
      - kademlia_network
    volumes:
      - ../:/code
      - ./init/node/:/init
      
networks:
  kademlia_network:

